import React, { useMemo } from 'react';
import ReactApexChart from 'react-apexcharts';
import { getCarrierColor, formatEnergy, formatPercentage } from '../../utils/pypsaUtils';

const EnergyMixChart = ({ data }) => {
  const chartData = useMemo(() => {
    if (!data || !data.energy_mix || data.energy_mix.length === 0) return null;

    return data.energy_mix.sort((a, b) => b.Energy_MWh - a.Energy_MWh);
  }, [data]);

  if (!chartData) {
    return (
      <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-8 text-center">
        <p className="text-slate-500">No energy mix data available</p>
      </div>
    );
  }

  const carriers = chartData.map(d => d.Carrier);
  const energies = chartData.map(d => d.Energy_MWh);
  const colors = carriers.map(carrier => getCarrierColor(carrier));
  const totalEnergy = energies.reduce((a, b) => a + b, 0);

  const chartOptions = {
    chart: {
      type: 'donut',
      animations: {
        enabled: true
      }
    },
    labels: carriers,
    colors: colors,
    legend: {
      position: 'right',
      fontSize: '14px',
      formatter: (seriesName, opts) => {
        const value = opts.w.globals.series[opts.seriesIndex];
        const percentage = ((value / totalEnergy) * 100).toFixed(1);
        return `${seriesName}: ${percentage}%`;
      }
    },
    dataLabels: {
      enabled: true,
      formatter: (val) => val.toFixed(1) + '%',
      style: {
        fontSize: '12px',
        fontWeight: 'bold'
      },
      dropShadow: {
        enabled: false
      }
    },
    plotOptions: {
      pie: {
        donut: {
          size: '65%',
          labels: {
            show: true,
            name: {
              show: true,
              fontSize: '16px'
            },
            value: {
              show: true,
              fontSize: '24px',
              fontWeight: 'bold',
              formatter: (val) => formatEnergy(val, 0)
            },
            total: {
              show: true,
              label: 'Total Generation',
              fontSize: '14px',
              color: '#64748b',
              formatter: () => formatEnergy(totalEnergy, 0)
            }
          }
        }
      }
    },
    tooltip: {
      y: {
        formatter: (val) => formatEnergy(val, 1)
      }
    },
    responsive: [{
      breakpoint: 768,
      options: {
        legend: {
          position: 'bottom'
        }
      }
    }]
  };

  return (
    <div className="bg-white rounded-lg shadow-sm border border-slate-200">
      {/* Header */}
      <div className="p-4 border-b border-slate-200">
        <h3 className="text-lg font-semibold text-slate-800">Energy Generation Mix</h3>
        <p className="text-sm text-slate-500">Total energy generated by carrier type</p>
      </div>

      {/* Chart */}
      <div className="p-4">
        <ReactApexChart
          options={chartOptions}
          series={energies}
          type="donut"
          height={400}
        />
      </div>

      {/* Statistics Table */}
      <div className="p-4 border-t border-slate-200">
        <h4 className="text-sm font-semibold text-slate-700 mb-3">Breakdown by Carrier</h4>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {chartData.map((item, index) => {
            const percentage = ((item.Energy_MWh / totalEnergy) * 100).toFixed(1);

            return (
              <div key={index} className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 hover:bg-slate-100 transition-colors">
                <div
                  className="w-4 h-4 rounded-full flex-shrink-0"
                  style={{ backgroundColor: getCarrierColor(item.Carrier) }}
                />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-slate-800 truncate">{item.Carrier}</p>
                  <p className="text-xs text-slate-600 font-mono">{formatEnergy(item.Energy_MWh, 1)}</p>
                </div>
                <div className="text-right flex-shrink-0">
                  <p className="text-sm font-bold text-slate-700">{percentage}%</p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Renewable Share Highlight */}
      {(() => {
        const renewableCarriers = ['solar', 'pv', 'wind', 'onwind', 'offwind', 'hydro', 'ror', 'reservoir', 'biomass', 'biogas'];
        const renewableEnergy = chartData
          .filter(item => renewableCarriers.some(re => item.Carrier.toLowerCase().includes(re)))
          .reduce((sum, item) => sum + item.Energy_MWh, 0);
        const renewableShare = ((renewableEnergy / totalEnergy) * 100).toFixed(1);

        return renewableShare > 0 && (
          <div className="mx-4 mb-4 p-4 rounded-lg bg-green-50 border border-green-200 flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-green-900">Renewable Energy Share</p>
              <p className="text-xs text-green-700">{formatEnergy(renewableEnergy, 1)} of total generation</p>
            </div>
            <div className="text-3xl font-bold text-green-600">{renewableShare}%</div>
          </div>
        );
      })()}
    </div>
  );
};

export default EnergyMixChart;
